# Generated by Django 4.0.3 on 2022-03-06 17:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_bid_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 6, 17, 1, 41, 27655, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 6, 17, 2, 15, 326366, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watching',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 6, 17, 2, 18, 830668, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
